# Generated by Django 5.0.1 on 2024-02-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'emp_login',
            },
        ),
        migrations.CreateModel(
            name='Employee_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eemail', models.CharField(max_length=255)),
                ('epassword', models.CharField(max_length=8)),
                ('ephone_no', models.IntegerField()),
                ('epersonal_document', models.ImageField(max_length=1000, upload_to='PersonalDocument/')),
                ('euser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
